<script type="text/javascript"
        src="https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.lightbox.js">
</script>

<div class="page-head">
    <h2 class="sub-title">Finalizando sua compra com PagSeguro</h2>
</div>
<script type="text/javascript">
    window.onload = function () {
        PagSeguroLightbox(
            {code: '<?= Mage::registry('code') ?>'}, {
                success: function (transactionCode) {
                    console.log(transactionCode)
                },
                abort: function (err) {
                    console.log(err)
                }
            });
    };
</script>

<table style="width:100%;">
    <tr>
        <td style="width:100%">
            Sa compra está em processo de finalização, aguarde um instante.<br>
            Casa a página de pagamento não iniciar automaticamente
            <a href="<?= Mage::registry('lightboxUrl') . Mage::registry('code') ?>" target="_blank">clique aqui</a>.
        </td>
    </tr>
</table>
